### ISSUE TITLE
Nested tuples of structs of tuples of...

### ISSUE THREAD

**Issue by LeonardJohard** [rafaqz/Flatten.jl#24]
When you have nested combination of tuples and structs it would be nice to extract other values (arrays in particular) from such a combination. Currently it seems you can work with either structs or tuples.

This is especially motivated by Zygote, where you can get such data structures if you differentiate structs (very common).

It seems most of the code is there already, but I cannot figure out how to hack it.

**Comment by rafaqz** [comment]
You can extract all `Array`s in the object to a `Tuple` of `Array`, then join them together:

```julia
cat(flatten(obj, AbstractArray)...)
```

But you could do something more efficient than `cat` I guess. You can get the _values_ of `StaticArrays` in the object into one `StaticArray`, here holding `Number`:

```julia
SVector(flatten(obj, Number))
```

Which should be essentially a compile-time operation. 


> It seems most of the code is there already, but I cannot figure out how to hack it.

Yes lol, recursive generated functions are hard to think about. I also wrote this a long time ago, It could be much cleaner.

But you shouldn't have to hack anything in the package - you can extract any types you want into a `Tuple`, anything you do to that is essentially what the package would have to do anyway, so just wrap it in a function. If it's really useful we could add it here - but it doesn't have to happen during the struct walking phase, it's cleaner to operate on the tuple output.

If you need to recursively walk into arrays that hold tuples that hold arrays, that's a very different operation to what this package does. This package untrolls the locations of particular types in a structually fixed object into a tuple of calls to `getfeild` - that then compiles down to a very short list of instructions to move registers around. 

Walking over arrays, in contrast, is a runtime operation, the compiler doesn't know how long they are. You would be better to write that from scratch, or find something else that does that, it probably exists.

**Comment by LeonardJohard** [comment]
Beautiful, seems I got it working with AbstractArray.

du = Flatten.flatten(dutuple, AbstractArray)
u = Flatten.flatten(ustruct, AbstractArray)
u = u .+ du #Gradient works

while

du = Flatten.flatten(dutuple, Number)
u = Flatten.flatten(ustruct, Number)

returns empty tuples (). Did I get it correctly that Number requires StaticArrays for the values to be flattened? In that case I understand the result.

**Comment by rafaqz** [comment]
Yes exactly.

This returns a tuple of `AbstractArray`
```julia
u = Flatten.flatten(ustruct, AbstractArray)
```

But you can't get what's inside an `Array` using Flatten.jl as it's a runtime detail - and more specifially because Flatten.jl works with `fieldnames` of an object. `Array`  has no field names:

```julia
julia> fieldnames(typeof([1,5,7]))
()
```

But `StaticArray` does:

```julia
julia> fieldnames(typeof(SA[1,5,7]))
(:data,)

julia> fieldnames(typeof(SA[1,5,7].data))
(1, 2, 3)
```

Which means that:
```julia
julia> Flatten.flatten(SA[1,5,7], Number)
(1, 5, 7)

julia> Flatten.flatten([1,5,7], Number)
()
```
