### ISSUE TITLE
Warning: Package Flatten does not have Unitful in its dependencies

### ISSUE THREAD

**Issue by briochemc** [rafaqz/Flatten.jl#3]
I don't know if this is intentional, but shouldn't Unitful be in the dependencies of Flatten? I have been getting this warning lately (both packages are up to date, Julia version 1.1.0):
```julia
julia> using Unitful, Flatten
┌ Warning: Package Flatten does not have Unitful in its dependencies:
│ - If you have Flatten checked out for development and have
│   added Unitful as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Flatten
└ Loading Unitful into Flatten from project dependency, future warnings for Flatten are suppressed.
```

In case it is useful, the `Pkg` status:
```julia
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [4c728ea3] Flatten v0.1.0
  [1986cc42] Unitful v0.14.0
```

**Comment by rafaqz** [comment]
I'm using Requires.jl so you only get unitful methods with `using Unitful`. But there should be some way of removing that warning I've been meaning to work that out...

**Comment by rafaqz** [comment]
Ok that's fixed on master, although the syntax people are suggesting to fix it is kinda weird. Let me know if that works for you.

**Comment by briochemc** [comment]
I didn't even know about Requires.jl! The warning does not bother me that much, I just thought I should mention it here for you in case you had not seen it for some reason 🙂

**Comment by briochemc** [comment]
Could you release a new version with these latest commits?

**Comment by rafaqz** [comment]
I'll try! I changed a few things I wasn't sure about, the internals are
standardized etc. Also I need to learn the new update method and my thesis
is due in a month...

**Comment by briochemc** [comment]
Oh sorry there is no rush :) 
Good luck with the thesis!

**Comment by briochemc** [comment]
Just to encourage you, I used the new update method and it is pretty easy! I'll see if I can help you with that :)
