### ISSUE TITLE
New reconstruct does not handle union types

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/Flatten.jl#32]
Yet another bug in the new, type-stable reconstruct implementation (sorry!).

structs which contain Union-typed fields, e.g:

```julia
struct A{T}
  val::Union{Missing,T}
end
```

cause `reconstruct` to fail because `fieldnames` is not defined on union types.

For now, the simplest solution is probably to just add a check for `isa(T,Union)` and fall back to a runtime type check in such cases (I don't foresee this being a problem in use cases such as `ModelParameters.jl`). And in general, this is the most conservative solution since there is no way to generate type stable code for arbitrary union types. However, it might be possible to handle `Union{Missing,...}` and `Union{Nothing,...}` in a special way that preserves type-stability. I would have to think more about it, though, and I don't see this being a particularly meaningful use-case any time soon.

**Comment by ConnectedSystems** [comment]
Ah, this might explain the issue raised [here](https://github.com/rafaqz/ModelParameters.jl/issues/28)

**Comment by bgroenks96** [comment]
Yeah... sorry! I just wanted it to be type stable :cold_sweat:

**Comment by rafaqz** [comment]
There was always going to be something broken with that change, thanks for catching it @ConnectedSystems
