### ISSUE TITLE
Issue with subtyping

### ISSUE THREAD

**Issue by briochemc** [rafaqz/Flatten.jl#7]
The new version fails silently if I use subtyping when defining a flattenable struct... I'm not sure what's going on. Could you have a look? MWE:
```julia
julia> @flattenable mutable struct Baz{X} <: AbstractVector{X}
           x::X | true
           y::X | false
           z::X | true
       end
flattenable (generic function with 24 methods)

julia> foo = Baz(1.0, 2.0, 3.0) ; # no show method so hide output

julia> flattenable(foo)
(true, false, true)

julia> flatten(foo) # Should give (1.0, 3.0) instead of an empty tuple
()
```
Not that this does happen when I omit the `<: AbstractVector{X}` subtype, hence the title of this issue. (FWIW I sort of need that subtype to pass it to other packages that enforce it...)

**Comment by rafaqz** [comment]
Thats weird. Guess there had to be a few hiccups to sort out.

**Comment by briochemc** [comment]
I edited my post as I just realized it two typos that could have been misleading. I.e., there is no problem when there is no subtyping.

Anyway, any ideas on what's going on? Maybe I can help? (But I would not know where to start looking)

**Comment by rafaqz** [comment]
Sorry this was actually obvious. The default behaviour was to ignore all `<: AbstractArray` as they mostly can't be flattened. But I realise it doesn't really make sense for cases like this, and StaticArrays. I've remove that on master and the default wont ignore anything now.
