### ISSUE TITLE
Metaflatten into vector

### ISSUE THREAD

**Issue by BenjaminBorn** [rafaqz/Flatten.jl#8]
In version 0.1.0, I used to be able to directly output `metaflatten()` into a vector like this:
```
using Parameters, Flatten, Distributions
import Flatten: flattenable
using FieldMetadata
import FieldMetadata: @prior
@metadata prior nothing

@flattenable @prior @with_kw struct ModelParameters{T}
    θ_π::T = 2.0   | Normal(1.7, 0.3)     | true 
    θ_Y::T = 0.125 | Normal(0.125, 0.05) | true
end

m_par = ModelParameters()
priors_vec = metaflatten(Vector, m_par, prior)
```

But now with version 0.2.0 I get an error message

> MethodError: no method matching metaflatten(::Type{Array{T,1} where T}, ::ModelParameters{Float64}, ::typeof(prior))
Closest candidates are:
  metaflatten(::I, !Matched::Function, ::Function, !Matched::Type{U}, !Matched::Type{I}, !Matched::Any, !Matched::Any) where {U, I} at /Users/bborn/.julia/packages/Flatten/GC9cP/src/Flatten.jl:420
  metaflatten(::U, !Matched::Function, ::Function, !Matched::Type{U}, !Matched::Type{I}, !Matched::Any, !Matched::Any) where {U, I} at /Users/bborn/.julia/packages/Flatten/GC9cP/src/Flatten.jl:421
  metaflatten(::Any, !Matched::Function, ::Function) at /Users/bborn/.julia/packages/Flatten/GC9cP/src/Flatten.jl:415
  ...
top-level scope at none:0

Was that intended? Should I just `collect()` the tuple from metaflatten or is the old behaviour still available.

Thanks for your help! Benjamin

**Comment by rafaqz** [comment]
As I added all the other arguments for specifying what types to flatten, I got rid of `flatten(Vector, x) ` It started to look confusing when you write something like `flatten(Vector, x, Int, AbstractArray)`

It just had the line `flatten(Vector, x) = [flatten(x)...]` internally.  So it actually uses less characters for you to  just write the `[flatten(x)...] `yourself, and makes it explicit that this package internally flattens to tuples, not vectors.

I could have been a bit clearer that that had happened. We are still in low version numbers, but I hope this is the last major syntax change.

Edit: You will also get better performance if you just leave everything as tuples when possible.

**Comment by BenjaminBorn** [comment]
Thanks a lot for the quick answer. I understand the change and also that this is still pre-1.0. Was just confused because my codes broke after updating.

And thanks again for this amazing package. It (plus FieldMetaData.jl) has made my life much easier!
