### ISSUE TITLE
How to not flattening recursively?

### ISSUE THREAD

**Issue by briochemc** [rafaqz/Flatten.jl#9]
It turns out the latest update breaks a few things for me.I'm not sure exactly what the issue(s) is (are), but I need to use complex, dual, and hyperdual types and `flatten` used to work seemlessly with those but not anymore. MWE of unexpected behavior for me:
```julia
julia> using Flatten

julia> import Flatten: flattenable

julia> @flattenable mutable struct Baz{X} <: AbstractVector{X}
                  x::X | true
                  y::X | false
                  z::X | true
              end
flattenable (generic function with 12 methods)

julia> baz = Baz(1.0 + 1.0im, 2.0 + 2.0im, 3.0 + 3.0im) ;

julia> flatten(baz) # `flatten` used to give `[1.0 + 1.0im, 3.0 + 3.0im]`
(1.0, 1.0, 3.0, 3.0)
``` 
My issue is that I want my struct `Baz{X}` to be a subtype of `AbstractVector{X}` and such that its flattenable part behaves like a vector. This was "easy" with the old behavior because I could define the equivalent `AbstractVector{X}` operations by manipulating the flattened vector, promoting things if needed, and reconstructing after. 

That is, for example, I made `2Baz(1.0, 2.0, 3.0) == Baz(2.0, 2.0, 6.0)` work (which still works for my case). I also had `im * Baz(1.0, 2.0, 3.0) == Baz(1.0im, 2.0+0.0im, 3.0im)` working, but **this does not work anymore with the new version, because `flatten` now flattens the `Complex{Float64}` elements, too**. 

For the details of doing `im * Baz(1.0, 2.0, 3.0)`: I used to flatten `Baz(1.0, 2.0, 3.0)` into `[1.0, 3.0]` (using `collect`), and then multiply it by `im`, which gives `[1.0im, 3.0im]`. But I cannot reconstruct from the vector `[1.0im, 3.0im]` (even after promoting the "base" object, i.e.,  `reconstruct(Baz(1.0+0.0im, 2.0+0.0im, 3.0+0.0im), [1.0im, 3.0im])` fails), since I guess it expects a 4-element `Float64` vector, `[0.0, 1.0, 0.0, 3.0]` instead of the 2-element `Complex{Float64}` vector `[1.0im, 3.0im]`. 

Hence, I feel like one solution for me would be to have an option to avoid having `flatten` be applied recursively so that the `Complex{Float64}` elements remain untouched. But maybe this is not an option anymore. In any case, how would you make these `AbstractVector{X}` operations work with the new Flatten version? Any help appreciated!

I'm sorry if I am confusing, it's just that I am confused myself and I'm having a hard time figuring out what exactly is the issue here and what's the best solution for me.

**Comment by briochemc** [comment]
One solution is to use flatten the vector twice if it is complex, but it looks ugly:
```julia
flatten(tuple([flatten(vi) for vi in v]...))
```

Another thing that I find strange is that reconstruct does not complain if there are too many elements in the tuple, e.g.:
```julia
reconstruct(Baz(0.0, 0.0, 0.0), (1.0, 2.0, 3.0, 4.0))
```
works despite `Baz` having only 3 fields... Is that intended? (Sorry if I am mixing issues here, just trying to fix my code 😄 )

**Comment by rafaqz** [comment]
Oh this is because I made the default `Real`. I don't know what the default should be honestly...

But its an easy fix. The idea is that you can flatten anything you want to:

```julia
# Flatten Number
julia> flatten(baz, Number) # `flatten` used to give `[1.0 + 1.0im, 3.0 + 3.0im]`
(1.0 + 1.0im, 3.0 + 3.0im)

# Specify Complex only
julia> flatten(baz, Complex) # `flatten` used to give `[1.0 + 1.0im, 3.0 + 3.0im]`
(1.0 + 1.0im, 3.0 + 3.0im)

# Or if you need to be specific
julia> flatten(baz, Union{Complex,Real}) # `flatten` used to give `[1.0 + 1.0im, 3.0 + 3.0im]`
(1.0 + 1.0im, 3.0 + 3.0im)
```

For the second issue, no it never cared if the tuple/vector data is too long.... I could make it check the length for tuples, but we can't for vectors because it's runtime information. 

Edit: I guess I could check the length of the vector against the number of fields filled after its all done at runtime. It probably makes sense to enforce that.

Edit 2: also bear with me here, the new changes mean this package can be used for a lot more things, but I had to break a few of the old syntax to get there - but you can still do everything it could do before, far more actually. Most of the behaviour is in the new docs pages, but let me know what isn't covered well.

**Comment by briochemc** [comment]
Oh thanks I did not know I could specify the type like that, I think I can get away with just that :) I’ll try it and let you know!

**Comment by briochemc** [comment]
OK specifying `Number` when calling `flatten` and `reconstruct` fixed my issues (works with `Complex`, `Dual` and `Hyper` now! So thank you again!

That being said, I think you might want to address that default value choice by checking with more educated Julia people than me 😅 

And by the way, yes, I think the new version and its expanded "scope" is really cool! Great job IMHO!
